### DISCUSSION TITLE
How to set custom image as icon in 2.1.1?

### DISCUSSION THREAD

**Discussion by andreystavitsky** [darioielardi/flutter_speed_dial#108] [Q&A] [answered]
If I set label: Image.Asset() then button shape go rectangle with rounded corners. ImageIcon can't be set as "icon" because it requires IconData instead of Icon. iconTheme parameter also requires IconThemeData instead of IconTheme.

**Comment by prateekmedia** [comment, marked as answer]
Just use the latest version provided in the git repo and use the child and activeChild property, you could also center your image if it doesn't fits well.

```
  flutter_speed_dial:
    git:
      url: git://github.com/darioielardi/flutter_speed_dial.git
      ref: master
```
