### ISSUE TITLE
Nullsafety support 

### ISSUE THREAD

**Issue by kw2019ltd** [darioielardi/flutter_speed_dial#120]
can you Please migrate to null safety.

https://dart.dev/null-safety/migration-guide#step1-wait

**Comment by prateekmedia** [comment]
> can you Please migrate to null safety.
> 
> https://dart.dev/null-safety/migration-guide#step1-wait
<details>
<summary>NO</summary>

Cause We already have it, you can checkout the nullsafety branch now to enjoy all the benefits of it.
```yaml
  flutter_speed_dial:
    git:
      url: git://github.com/darioielardi/flutter_speed_dial.git
      ref: nullsafety
```

</details>

Expand it to know more! Also these type of things should go into discussions and not an issue.
