### ISSUE TITLE
onPress removes the open and close functionality

### ISSUE THREAD

**Issue by baurmax1998** [darioielardi/flutter_speed_dial#126]
Hi i tried to add an action to the close-button, but when i implement the onPress-function i cant open the menu anymore. Even with the openCloseDial functionality.

**Comment by prateekmedia** [comment]
> Hi i tried to add an action to the close-button, but when i implement the onPress-function i cant open the menu anymore. Even with the openCloseDial functionality.

Are you on master branch?

**Comment by baurmax1998** [comment]
i am using   flutter_speed_dial: ^2.1.1

**Comment by prateekmedia** [comment]
> i am using flutter_speed_dial: ^2.1.1

That has old code, first let's be on the same version, replace your normal flutter_speed_dial line in pubspec.yaml with 
```yaml
  flutter_speed_dial:
    git:
      url: https://github.com/darioielardi/flutter_speed_dial.git
      ref: master
```

or if you want a static version then

```yaml
  flutter_speed_dial:
    git:
      url: https://github.com/darioielardi/flutter_speed_dial.git
      ref: 3.0.0
```

If the issue still persists then report here
